/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * AuthoringStatsSummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class AuthoringStatsSummary {
  @SerializedName("changedFsnCount")
  private Long changedFsnCount = null;

  @SerializedName("executionTime")
  private OffsetDateTime executionTime = null;

  @SerializedName("inactivatedConceptsCount")
  private Long inactivatedConceptsCount = null;

  @SerializedName("inactivatedSynonymsCount")
  private Long inactivatedSynonymsCount = null;

  @SerializedName("newConceptsCount")
  private Long newConceptsCount = null;

  @SerializedName("newSynonymsForExistingConceptsCount")
  private Long newSynonymsForExistingConceptsCount = null;

  @SerializedName("reactivatedConceptsCount")
  private Long reactivatedConceptsCount = null;

  @SerializedName("reactivatedSynonymsCount")
  private Long reactivatedSynonymsCount = null;

  @SerializedName("title")
  private String title = null;

  public AuthoringStatsSummary changedFsnCount(Long changedFsnCount) {
    this.changedFsnCount = changedFsnCount;
    return this;
  }

   /**
   * Get changedFsnCount
   * @return changedFsnCount
  **/
  @ApiModelProperty(value = "")
  public Long getChangedFsnCount() {
    return changedFsnCount;
  }

  public void setChangedFsnCount(Long changedFsnCount) {
    this.changedFsnCount = changedFsnCount;
  }

  public AuthoringStatsSummary executionTime(OffsetDateTime executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(OffsetDateTime executionTime) {
    this.executionTime = executionTime;
  }

  public AuthoringStatsSummary inactivatedConceptsCount(Long inactivatedConceptsCount) {
    this.inactivatedConceptsCount = inactivatedConceptsCount;
    return this;
  }

   /**
   * Get inactivatedConceptsCount
   * @return inactivatedConceptsCount
  **/
  @ApiModelProperty(value = "")
  public Long getInactivatedConceptsCount() {
    return inactivatedConceptsCount;
  }

  public void setInactivatedConceptsCount(Long inactivatedConceptsCount) {
    this.inactivatedConceptsCount = inactivatedConceptsCount;
  }

  public AuthoringStatsSummary inactivatedSynonymsCount(Long inactivatedSynonymsCount) {
    this.inactivatedSynonymsCount = inactivatedSynonymsCount;
    return this;
  }

   /**
   * Get inactivatedSynonymsCount
   * @return inactivatedSynonymsCount
  **/
  @ApiModelProperty(value = "")
  public Long getInactivatedSynonymsCount() {
    return inactivatedSynonymsCount;
  }

  public void setInactivatedSynonymsCount(Long inactivatedSynonymsCount) {
    this.inactivatedSynonymsCount = inactivatedSynonymsCount;
  }

  public AuthoringStatsSummary newConceptsCount(Long newConceptsCount) {
    this.newConceptsCount = newConceptsCount;
    return this;
  }

   /**
   * Get newConceptsCount
   * @return newConceptsCount
  **/
  @ApiModelProperty(value = "")
  public Long getNewConceptsCount() {
    return newConceptsCount;
  }

  public void setNewConceptsCount(Long newConceptsCount) {
    this.newConceptsCount = newConceptsCount;
  }

  public AuthoringStatsSummary newSynonymsForExistingConceptsCount(Long newSynonymsForExistingConceptsCount) {
    this.newSynonymsForExistingConceptsCount = newSynonymsForExistingConceptsCount;
    return this;
  }

   /**
   * Get newSynonymsForExistingConceptsCount
   * @return newSynonymsForExistingConceptsCount
  **/
  @ApiModelProperty(value = "")
  public Long getNewSynonymsForExistingConceptsCount() {
    return newSynonymsForExistingConceptsCount;
  }

  public void setNewSynonymsForExistingConceptsCount(Long newSynonymsForExistingConceptsCount) {
    this.newSynonymsForExistingConceptsCount = newSynonymsForExistingConceptsCount;
  }

  public AuthoringStatsSummary reactivatedConceptsCount(Long reactivatedConceptsCount) {
    this.reactivatedConceptsCount = reactivatedConceptsCount;
    return this;
  }

   /**
   * Get reactivatedConceptsCount
   * @return reactivatedConceptsCount
  **/
  @ApiModelProperty(value = "")
  public Long getReactivatedConceptsCount() {
    return reactivatedConceptsCount;
  }

  public void setReactivatedConceptsCount(Long reactivatedConceptsCount) {
    this.reactivatedConceptsCount = reactivatedConceptsCount;
  }

  public AuthoringStatsSummary reactivatedSynonymsCount(Long reactivatedSynonymsCount) {
    this.reactivatedSynonymsCount = reactivatedSynonymsCount;
    return this;
  }

   /**
   * Get reactivatedSynonymsCount
   * @return reactivatedSynonymsCount
  **/
  @ApiModelProperty(value = "")
  public Long getReactivatedSynonymsCount() {
    return reactivatedSynonymsCount;
  }

  public void setReactivatedSynonymsCount(Long reactivatedSynonymsCount) {
    this.reactivatedSynonymsCount = reactivatedSynonymsCount;
  }

  public AuthoringStatsSummary title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthoringStatsSummary authoringStatsSummary = (AuthoringStatsSummary) o;
    return Objects.equals(this.changedFsnCount, authoringStatsSummary.changedFsnCount) &&
        Objects.equals(this.executionTime, authoringStatsSummary.executionTime) &&
        Objects.equals(this.inactivatedConceptsCount, authoringStatsSummary.inactivatedConceptsCount) &&
        Objects.equals(this.inactivatedSynonymsCount, authoringStatsSummary.inactivatedSynonymsCount) &&
        Objects.equals(this.newConceptsCount, authoringStatsSummary.newConceptsCount) &&
        Objects.equals(this.newSynonymsForExistingConceptsCount, authoringStatsSummary.newSynonymsForExistingConceptsCount) &&
        Objects.equals(this.reactivatedConceptsCount, authoringStatsSummary.reactivatedConceptsCount) &&
        Objects.equals(this.reactivatedSynonymsCount, authoringStatsSummary.reactivatedSynonymsCount) &&
        Objects.equals(this.title, authoringStatsSummary.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedFsnCount, executionTime, inactivatedConceptsCount, inactivatedSynonymsCount, newConceptsCount, newSynonymsForExistingConceptsCount, reactivatedConceptsCount, reactivatedSynonymsCount, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthoringStatsSummary {\n");
    
    sb.append("    changedFsnCount: ").append(toIndentedString(changedFsnCount)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("    inactivatedConceptsCount: ").append(toIndentedString(inactivatedConceptsCount)).append("\n");
    sb.append("    inactivatedSynonymsCount: ").append(toIndentedString(inactivatedSynonymsCount)).append("\n");
    sb.append("    newConceptsCount: ").append(toIndentedString(newConceptsCount)).append("\n");
    sb.append("    newSynonymsForExistingConceptsCount: ").append(toIndentedString(newSynonymsForExistingConceptsCount)).append("\n");
    sb.append("    reactivatedConceptsCount: ").append(toIndentedString(reactivatedConceptsCount)).append("\n");
    sb.append("    reactivatedSynonymsCount: ").append(toIndentedString(reactivatedSynonymsCount)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

