/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * BranchPojo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class BranchPojo {
  @SerializedName("base")
  private OffsetDateTime base = null;

  @SerializedName("baseTimestamp")
  private Long baseTimestamp = null;

  @SerializedName("containsContent")
  private Boolean containsContent = null;

  @SerializedName("creation")
  private OffsetDateTime creation = null;

  @SerializedName("creationTimestamp")
  private Long creationTimestamp = null;

  @SerializedName("head")
  private OffsetDateTime head = null;

  @SerializedName("headTimestamp")
  private Long headTimestamp = null;

  @SerializedName("locked")
  private Boolean locked = null;

  @SerializedName("metadata")
  private Object metadata = null;

  @SerializedName("path")
  private String path = null;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    UP_TO_DATE("UP_TO_DATE"),
    
    FORWARD("FORWARD"),
    
    BEHIND("BEHIND"),
    
    DIVERGED("DIVERGED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("versionsReplacedCounts")
  private Map<String, Integer> versionsReplacedCounts = null;

  public BranchPojo base(OffsetDateTime base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getBase() {
    return base;
  }

  public void setBase(OffsetDateTime base) {
    this.base = base;
  }

  public BranchPojo baseTimestamp(Long baseTimestamp) {
    this.baseTimestamp = baseTimestamp;
    return this;
  }

   /**
   * Get baseTimestamp
   * @return baseTimestamp
  **/
  @ApiModelProperty(value = "")
  public Long getBaseTimestamp() {
    return baseTimestamp;
  }

  public void setBaseTimestamp(Long baseTimestamp) {
    this.baseTimestamp = baseTimestamp;
  }

  public BranchPojo containsContent(Boolean containsContent) {
    this.containsContent = containsContent;
    return this;
  }

   /**
   * Get containsContent
   * @return containsContent
  **/
  @ApiModelProperty(value = "")
  public Boolean isContainsContent() {
    return containsContent;
  }

  public void setContainsContent(Boolean containsContent) {
    this.containsContent = containsContent;
  }

  public BranchPojo creation(OffsetDateTime creation) {
    this.creation = creation;
    return this;
  }

   /**
   * Get creation
   * @return creation
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreation() {
    return creation;
  }

  public void setCreation(OffsetDateTime creation) {
    this.creation = creation;
  }

  public BranchPojo creationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

   /**
   * Get creationTimestamp
   * @return creationTimestamp
  **/
  @ApiModelProperty(value = "")
  public Long getCreationTimestamp() {
    return creationTimestamp;
  }

  public void setCreationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  public BranchPojo head(OffsetDateTime head) {
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getHead() {
    return head;
  }

  public void setHead(OffsetDateTime head) {
    this.head = head;
  }

  public BranchPojo headTimestamp(Long headTimestamp) {
    this.headTimestamp = headTimestamp;
    return this;
  }

   /**
   * Get headTimestamp
   * @return headTimestamp
  **/
  @ApiModelProperty(value = "")
  public Long getHeadTimestamp() {
    return headTimestamp;
  }

  public void setHeadTimestamp(Long headTimestamp) {
    this.headTimestamp = headTimestamp;
  }

  public BranchPojo locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @ApiModelProperty(value = "")
  public Boolean isLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }

  public BranchPojo metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public BranchPojo path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public BranchPojo state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public BranchPojo versionsReplacedCounts(Map<String, Integer> versionsReplacedCounts) {
    this.versionsReplacedCounts = versionsReplacedCounts;
    return this;
  }

  public BranchPojo putVersionsReplacedCountsItem(String key, Integer versionsReplacedCountsItem) {
    if (this.versionsReplacedCounts == null) {
      this.versionsReplacedCounts = new HashMap<String, Integer>();
    }
    this.versionsReplacedCounts.put(key, versionsReplacedCountsItem);
    return this;
  }

   /**
   * Get versionsReplacedCounts
   * @return versionsReplacedCounts
  **/
  @ApiModelProperty(value = "")
  public Map<String, Integer> getVersionsReplacedCounts() {
    return versionsReplacedCounts;
  }

  public void setVersionsReplacedCounts(Map<String, Integer> versionsReplacedCounts) {
    this.versionsReplacedCounts = versionsReplacedCounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchPojo branchPojo = (BranchPojo) o;
    return Objects.equals(this.base, branchPojo.base) &&
        Objects.equals(this.baseTimestamp, branchPojo.baseTimestamp) &&
        Objects.equals(this.containsContent, branchPojo.containsContent) &&
        Objects.equals(this.creation, branchPojo.creation) &&
        Objects.equals(this.creationTimestamp, branchPojo.creationTimestamp) &&
        Objects.equals(this.head, branchPojo.head) &&
        Objects.equals(this.headTimestamp, branchPojo.headTimestamp) &&
        Objects.equals(this.locked, branchPojo.locked) &&
        Objects.equals(this.metadata, branchPojo.metadata) &&
        Objects.equals(this.path, branchPojo.path) &&
        Objects.equals(this.state, branchPojo.state) &&
        Objects.equals(this.versionsReplacedCounts, branchPojo.versionsReplacedCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, baseTimestamp, containsContent, creation, creationTimestamp, head, headTimestamp, locked, metadata, path, state, versionsReplacedCounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchPojo {\n");
    
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    baseTimestamp: ").append(toIndentedString(baseTimestamp)).append("\n");
    sb.append("    containsContent: ").append(toIndentedString(containsContent)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    headTimestamp: ").append(toIndentedString(headTimestamp)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    versionsReplacedCounts: ").append(toIndentedString(versionsReplacedCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

