/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConceptMini;
import java.io.IOException;

/**
 * BrowserDescriptionSearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class BrowserDescriptionSearchResult implements Comparable<BrowserDescriptionSearchResult>{
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("concept")
  private ConceptMini concept = null;

  @SerializedName("languageCode")
  private String languageCode = null;

  @SerializedName("module")
  private String module = null;

  @SerializedName("term")
  private String term = null;

  public BrowserDescriptionSearchResult active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public BrowserDescriptionSearchResult concept(ConceptMini concept) {
    this.concept = concept;
    return this;
  }

   /**
   * Get concept
   * @return concept
  **/
  @ApiModelProperty(value = "")
  public ConceptMini getConcept() {
    return concept;
  }

  public void setConcept(ConceptMini concept) {
    this.concept = concept;
  }

  public BrowserDescriptionSearchResult languageCode(String languageCode) {
    this.languageCode = languageCode;
    return this;
  }

   /**
   * Get languageCode
   * @return languageCode
  **/
  @ApiModelProperty(value = "")
  public String getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  public BrowserDescriptionSearchResult module(String module) {
    this.module = module;
    return this;
  }

   /**
   * Get module
   * @return module
  **/
  @ApiModelProperty(value = "")
  public String getModule() {
    return module;
  }

  public void setModule(String module) {
    this.module = module;
  }

  public BrowserDescriptionSearchResult term(String term) {
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  @ApiModelProperty(value = "")
  public String getTerm() {
    return term;
  }

  public void setTerm(String term) {
    this.term = term;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrowserDescriptionSearchResult browserDescriptionSearchResult = (BrowserDescriptionSearchResult) o;
    return Objects.equals(this.active, browserDescriptionSearchResult.active) &&
        Objects.equals(this.concept, browserDescriptionSearchResult.concept) &&
        Objects.equals(this.languageCode, browserDescriptionSearchResult.languageCode) &&
        Objects.equals(this.module, browserDescriptionSearchResult.module) &&
        Objects.equals(this.term, browserDescriptionSearchResult.term);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, concept, languageCode, module, term);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrowserDescriptionSearchResult {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    concept: ").append(toIndentedString(concept)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    module: ").append(toIndentedString(module)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  // scoring
  private int score = 0;

  public int getScore() {
    return score;
  }

  public void setScore(int score) {
    this.score = score;
  }

  // to sort list of BrowserDescriptionSearchResult by score
  @Override
  public int compareTo(BrowserDescriptionSearchResult o) {
    int score = ((BrowserDescriptionSearchResult) o).getScore();
    // ascending order
    return this.score - score;
  }
}

