/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CollectionTypeReferences;
import java.io.IOException;

/**
 * ConceptReferencesResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class ConceptReferencesResult {
  @SerializedName("limit")
  private Long limit = null;

  @SerializedName("offset")
  private Long offset = null;

  @SerializedName("referencesByType")
  private CollectionTypeReferences referencesByType = null;

  @SerializedName("total")
  private Long total = null;

  public ConceptReferencesResult limit(Long limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @ApiModelProperty(value = "")
  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public ConceptReferencesResult offset(Long offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @ApiModelProperty(value = "")
  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public ConceptReferencesResult referencesByType(CollectionTypeReferences referencesByType) {
    this.referencesByType = referencesByType;
    return this;
  }

   /**
   * Get referencesByType
   * @return referencesByType
  **/
  @ApiModelProperty(value = "")
  public CollectionTypeReferences getReferencesByType() {
    return referencesByType;
  }

  public void setReferencesByType(CollectionTypeReferences referencesByType) {
    this.referencesByType = referencesByType;
  }

  public ConceptReferencesResult total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConceptReferencesResult conceptReferencesResult = (ConceptReferencesResult) o;
    return Objects.equals(this.limit, conceptReferencesResult.limit) &&
        Objects.equals(this.offset, conceptReferencesResult.offset) &&
        Objects.equals(this.referencesByType, conceptReferencesResult.referencesByType) &&
        Objects.equals(this.total, conceptReferencesResult.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, offset, referencesByType, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConceptReferencesResult {\n");
    
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    referencesByType: ").append(toIndentedString(referencesByType)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

