/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Expression
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class Expression {
  @SerializedName("attributes")
  private List<ExpressionAttribute> attributes = null;

  @SerializedName("concepts")
  private List<ConceptMicro> concepts = null;

  @SerializedName("groups")
  private List<ExpressionGroup> groups = null;

  public Expression attributes(List<ExpressionAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Expression addAttributesItem(ExpressionAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<ExpressionAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public List<ExpressionAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<ExpressionAttribute> attributes) {
    this.attributes = attributes;
  }

  public Expression concepts(List<ConceptMicro> concepts) {
    this.concepts = concepts;
    return this;
  }

  public Expression addConceptsItem(ConceptMicro conceptsItem) {
    if (this.concepts == null) {
      this.concepts = new ArrayList<ConceptMicro>();
    }
    this.concepts.add(conceptsItem);
    return this;
  }

   /**
   * Get concepts
   * @return concepts
  **/
  @ApiModelProperty(value = "")
  public List<ConceptMicro> getConcepts() {
    return concepts;
  }

  public void setConcepts(List<ConceptMicro> concepts) {
    this.concepts = concepts;
  }

  public Expression groups(List<ExpressionGroup> groups) {
    this.groups = groups;
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<ExpressionGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<ExpressionGroup> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Expression expression = (Expression) o;
    return Objects.equals(this.attributes, expression.attributes) &&
        Objects.equals(this.concepts, expression.concepts) &&
        Objects.equals(this.groups, expression.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, concepts, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Expression {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    concepts: ").append(toIndentedString(concepts)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

