/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExpressionAttribute;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExpressionGroup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class ExpressionGroup {
  @SerializedName("attributes")
  private List<ExpressionAttribute> attributes = null;

  public ExpressionGroup attributes(List<ExpressionAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ExpressionGroup addAttributesItem(ExpressionAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<ExpressionAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public List<ExpressionAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<ExpressionAttribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpressionGroup expressionGroup = (ExpressionGroup) o;
    return Objects.equals(this.attributes, expressionGroup.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpressionGroup {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

