/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConceptMini;
import io.swagger.client.model.ReferenceSetMember;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * RefSetMemberPageWithBucketAggregationsReferenceSetMember
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class RefSetMemberPageWithBucketAggregationsReferenceSetMember {
  @SerializedName("first")
  private Boolean first = null;

  @SerializedName("items")
  private List<ReferenceSetMember> items = null;

  @SerializedName("last")
  private Boolean last = null;

  @SerializedName("memberCountsByReferenceSet")
  private Map<String, Long> memberCountsByReferenceSet = null;

  @SerializedName("number")
  private Integer number = null;

  @SerializedName("numberOfElements")
  private Integer numberOfElements = null;

  @SerializedName("referenceSets")
  private Map<String, ConceptMini> referenceSets = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("totalElements")
  private Long totalElements = null;

  @SerializedName("totalPages")
  private Integer totalPages = null;

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember first(Boolean first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  @ApiModelProperty(value = "")
  public Boolean isFirst() {
    return first;
  }

  public void setFirst(Boolean first) {
    this.first = first;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember items(List<ReferenceSetMember> items) {
    this.items = items;
    return this;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember addItemsItem(ReferenceSetMember itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<ReferenceSetMember>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<ReferenceSetMember> getItems() {
    return items;
  }

  public void setItems(List<ReferenceSetMember> items) {
    this.items = items;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember last(Boolean last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/
  @ApiModelProperty(value = "")
  public Boolean isLast() {
    return last;
  }

  public void setLast(Boolean last) {
    this.last = last;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember memberCountsByReferenceSet(Map<String, Long> memberCountsByReferenceSet) {
    this.memberCountsByReferenceSet = memberCountsByReferenceSet;
    return this;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember putMemberCountsByReferenceSetItem(String key, Long memberCountsByReferenceSetItem) {
    if (this.memberCountsByReferenceSet == null) {
      this.memberCountsByReferenceSet = new HashMap<String, Long>();
    }
    this.memberCountsByReferenceSet.put(key, memberCountsByReferenceSetItem);
    return this;
  }

   /**
   * Get memberCountsByReferenceSet
   * @return memberCountsByReferenceSet
  **/
  @ApiModelProperty(value = "")
  public Map<String, Long> getMemberCountsByReferenceSet() {
    return memberCountsByReferenceSet;
  }

  public void setMemberCountsByReferenceSet(Map<String, Long> memberCountsByReferenceSet) {
    this.memberCountsByReferenceSet = memberCountsByReferenceSet;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember numberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * @return numberOfElements
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember referenceSets(Map<String, ConceptMini> referenceSets) {
    this.referenceSets = referenceSets;
    return this;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember putReferenceSetsItem(String key, ConceptMini referenceSetsItem) {
    if (this.referenceSets == null) {
      this.referenceSets = new HashMap<String, ConceptMini>();
    }
    this.referenceSets.put(key, referenceSetsItem);
    return this;
  }

   /**
   * Get referenceSets
   * @return referenceSets
  **/
  @ApiModelProperty(value = "")
  public Map<String, ConceptMini> getReferenceSets() {
    return referenceSets;
  }

  public void setReferenceSets(Map<String, ConceptMini> referenceSets) {
    this.referenceSets = referenceSets;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(value = "")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember totalElements(Long totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  @ApiModelProperty(value = "")
  public Long getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Long totalElements) {
    this.totalElements = totalElements;
  }

  public RefSetMemberPageWithBucketAggregationsReferenceSetMember totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefSetMemberPageWithBucketAggregationsReferenceSetMember refSetMemberPageWithBucketAggregationsReferenceSetMember = (RefSetMemberPageWithBucketAggregationsReferenceSetMember) o;
    return Objects.equals(this.first, refSetMemberPageWithBucketAggregationsReferenceSetMember.first) &&
        Objects.equals(this.items, refSetMemberPageWithBucketAggregationsReferenceSetMember.items) &&
        Objects.equals(this.last, refSetMemberPageWithBucketAggregationsReferenceSetMember.last) &&
        Objects.equals(this.memberCountsByReferenceSet, refSetMemberPageWithBucketAggregationsReferenceSetMember.memberCountsByReferenceSet) &&
        Objects.equals(this.number, refSetMemberPageWithBucketAggregationsReferenceSetMember.number) &&
        Objects.equals(this.numberOfElements, refSetMemberPageWithBucketAggregationsReferenceSetMember.numberOfElements) &&
        Objects.equals(this.referenceSets, refSetMemberPageWithBucketAggregationsReferenceSetMember.referenceSets) &&
        Objects.equals(this.size, refSetMemberPageWithBucketAggregationsReferenceSetMember.size) &&
        Objects.equals(this.totalElements, refSetMemberPageWithBucketAggregationsReferenceSetMember.totalElements) &&
        Objects.equals(this.totalPages, refSetMemberPageWithBucketAggregationsReferenceSetMember.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(first, items, last, memberCountsByReferenceSet, number, numberOfElements, referenceSets, size, totalElements, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefSetMemberPageWithBucketAggregationsReferenceSetMember {\n");
    
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    memberCountsByReferenceSet: ").append(toIndentedString(memberCountsByReferenceSet)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    referenceSets: ").append(toIndentedString(referenceSets)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

