/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CodeSystem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class CodeSystem {
  @SerializedName("branchPath")
  private String branchPath = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("dailyBuildAvailable")
  private Boolean dailyBuildAvailable = null;

  @SerializedName("defaultLanguageCode")
  private String defaultLanguageCode = null;

  @SerializedName("defaultLanguageReferenceSets")
  private List<String> defaultLanguageReferenceSets = null;

  @SerializedName("dependantVersion")
  private Integer dependantVersion = null;

  @SerializedName("languages")
  private Map<String, String> languages = null;

  @SerializedName("latestVersion")
  private CodeSystemVersion latestVersion = null;

  @SerializedName("modules")
  private List<ConceptMini> modules = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("shortName")
  private String shortName = null;

  public CodeSystem branchPath(String branchPath) {
    this.branchPath = branchPath;
    return this;
  }

   /**
   * Get branchPath
   * @return branchPath
  **/
  @ApiModelProperty(value = "")
  public String getBranchPath() {
    return branchPath;
  }

  public void setBranchPath(String branchPath) {
    this.branchPath = branchPath;
  }

  public CodeSystem countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public CodeSystem dailyBuildAvailable(Boolean dailyBuildAvailable) {
    this.dailyBuildAvailable = dailyBuildAvailable;
    return this;
  }

   /**
   * Get dailyBuildAvailable
   * @return dailyBuildAvailable
  **/
  @ApiModelProperty(value = "")
  public Boolean isDailyBuildAvailable() {
    return dailyBuildAvailable;
  }

  public void setDailyBuildAvailable(Boolean dailyBuildAvailable) {
    this.dailyBuildAvailable = dailyBuildAvailable;
  }

  public CodeSystem defaultLanguageCode(String defaultLanguageCode) {
    this.defaultLanguageCode = defaultLanguageCode;
    return this;
  }

   /**
   * Get defaultLanguageCode
   * @return defaultLanguageCode
  **/
  @ApiModelProperty(value = "")
  public String getDefaultLanguageCode() {
    return defaultLanguageCode;
  }

  public void setDefaultLanguageCode(String defaultLanguageCode) {
    this.defaultLanguageCode = defaultLanguageCode;
  }

  public CodeSystem defaultLanguageReferenceSets(List<String> defaultLanguageReferenceSets) {
    this.defaultLanguageReferenceSets = defaultLanguageReferenceSets;
    return this;
  }

  public CodeSystem addDefaultLanguageReferenceSetsItem(String defaultLanguageReferenceSetsItem) {
    if (this.defaultLanguageReferenceSets == null) {
      this.defaultLanguageReferenceSets = new ArrayList<String>();
    }
    this.defaultLanguageReferenceSets.add(defaultLanguageReferenceSetsItem);
    return this;
  }

   /**
   * Get defaultLanguageReferenceSets
   * @return defaultLanguageReferenceSets
  **/
  @ApiModelProperty(value = "")
  public List<String> getDefaultLanguageReferenceSets() {
    return defaultLanguageReferenceSets;
  }

  public void setDefaultLanguageReferenceSets(List<String> defaultLanguageReferenceSets) {
    this.defaultLanguageReferenceSets = defaultLanguageReferenceSets;
  }

  public CodeSystem dependantVersion(Integer dependantVersion) {
    this.dependantVersion = dependantVersion;
    return this;
  }

   /**
   * Get dependantVersion
   * @return dependantVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getDependantVersion() {
    return dependantVersion;
  }

  public void setDependantVersion(Integer dependantVersion) {
    this.dependantVersion = dependantVersion;
  }

  public CodeSystem languages(Map<String, String> languages) {
    this.languages = languages;
    return this;
  }

  public CodeSystem putLanguagesItem(String key, String languagesItem) {
    if (this.languages == null) {
      this.languages = new HashMap<String, String>();
    }
    this.languages.put(key, languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getLanguages() {
    return languages;
  }

  public void setLanguages(Map<String, String> languages) {
    this.languages = languages;
  }

  public CodeSystem latestVersion(CodeSystemVersion latestVersion) {
    this.latestVersion = latestVersion;
    return this;
  }

   /**
   * Get latestVersion
   * @return latestVersion
  **/
  @ApiModelProperty(value = "")
  public CodeSystemVersion getLatestVersion() {
    return latestVersion;
  }

  public void setLatestVersion(CodeSystemVersion latestVersion) {
    this.latestVersion = latestVersion;
  }

  public CodeSystem modules(List<ConceptMini> modules) {
    this.modules = modules;
    return this;
  }

   /**
   * Get modules
   * @return modules
  **/
  @ApiModelProperty(value = "")
  public List<ConceptMini> getModules() {
    return modules;
  }

  public void setModules(List<ConceptMini> modules) {
    this.modules = modules;
  }

  public CodeSystem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CodeSystem shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @ApiModelProperty(value = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeSystem codeSystem = (CodeSystem) o;
    return Objects.equals(this.branchPath, codeSystem.branchPath) &&
        Objects.equals(this.countryCode, codeSystem.countryCode) &&
        Objects.equals(this.dailyBuildAvailable, codeSystem.dailyBuildAvailable) &&
        Objects.equals(this.defaultLanguageCode, codeSystem.defaultLanguageCode) &&
        Objects.equals(this.defaultLanguageReferenceSets, codeSystem.defaultLanguageReferenceSets) &&
        Objects.equals(this.dependantVersion, codeSystem.dependantVersion) &&
        Objects.equals(this.languages, codeSystem.languages) &&
        Objects.equals(this.latestVersion, codeSystem.latestVersion) &&
        Objects.equals(this.modules, codeSystem.modules) &&
        Objects.equals(this.name, codeSystem.name) &&
        Objects.equals(this.shortName, codeSystem.shortName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchPath, countryCode, dailyBuildAvailable, defaultLanguageCode, defaultLanguageReferenceSets, dependantVersion, languages, latestVersion, modules, name, shortName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeSystem {\n");
    
    sb.append("    branchPath: ").append(toIndentedString(branchPath)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    dailyBuildAvailable: ").append(toIndentedString(dailyBuildAvailable)).append("\n");
    sb.append("    defaultLanguageCode: ").append(toIndentedString(defaultLanguageCode)).append("\n");
    sb.append("    defaultLanguageReferenceSets: ").append(toIndentedString(defaultLanguageReferenceSets)).append("\n");
    sb.append("    dependantVersion: ").append(toIndentedString(dependantVersion)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    latestVersion: ").append(toIndentedString(latestVersion)).append("\n");
    sb.append("    modules: ").append(toIndentedString(modules)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

