/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConceptMicro
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class ConceptMicro {
  @SerializedName("id")
  private String id = null;

  @SerializedName("primitive")
  private Boolean primitive = null;

  @SerializedName("term")
  private String term = null;

  public ConceptMicro id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConceptMicro primitive(Boolean primitive) {
    this.primitive = primitive;
    return this;
  }

   /**
   * Get primitive
   * @return primitive
  **/
  @ApiModelProperty(value = "")
  public Boolean isPrimitive() {
    return primitive;
  }

  public void setPrimitive(Boolean primitive) {
    this.primitive = primitive;
  }

  public ConceptMicro term(String term) {
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  @ApiModelProperty(value = "")
  public String getTerm() {
    return term;
  }

  public void setTerm(String term) {
    this.term = term;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConceptMicro conceptMicro = (ConceptMicro) o;
    return Objects.equals(this.id, conceptMicro.id) &&
        Objects.equals(this.primitive, conceptMicro.primitive) &&
        Objects.equals(this.term, conceptMicro.term);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, primitive, term);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConceptMicro {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    primitive: ").append(toIndentedString(primitive)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

