/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Relationship;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InboundRelationshipsResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class InboundRelationshipsResult {
  @SerializedName("inboundRelationships")
  private List<Relationship> inboundRelationships = null;

  @SerializedName("total")
  private Integer total = null;

  public InboundRelationshipsResult inboundRelationships(List<Relationship> inboundRelationships) {
    this.inboundRelationships = inboundRelationships;
    return this;
  }

  public InboundRelationshipsResult addInboundRelationshipsItem(Relationship inboundRelationshipsItem) {
    if (this.inboundRelationships == null) {
      this.inboundRelationships = new ArrayList<Relationship>();
    }
    this.inboundRelationships.add(inboundRelationshipsItem);
    return this;
  }

   /**
   * Get inboundRelationships
   * @return inboundRelationships
  **/
  @ApiModelProperty(value = "")
  public List<Relationship> getInboundRelationships() {
    return inboundRelationships;
  }

  public void setInboundRelationships(List<Relationship> inboundRelationships) {
    this.inboundRelationships = inboundRelationships;
  }

  public InboundRelationshipsResult total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundRelationshipsResult inboundRelationshipsResult = (InboundRelationshipsResult) o;
    return Objects.equals(this.inboundRelationships, inboundRelationshipsResult.inboundRelationships) &&
        Objects.equals(this.total, inboundRelationshipsResult.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inboundRelationships, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundRelationshipsResult {\n");
    
    sb.append("    inboundRelationships: ").append(toIndentedString(inboundRelationships)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

