/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CollectionConceptMini;
import io.swagger.client.model.ConceptMini;
import java.io.IOException;

/**
 * TypeReferences
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T10:22:15.067Z")
public class TypeReferences {
  @SerializedName("referenceType")
  private ConceptMini referenceType = null;

  @SerializedName("referencingConcepts")
  private CollectionConceptMini referencingConcepts = null;

  public TypeReferences referenceType(ConceptMini referenceType) {
    this.referenceType = referenceType;
    return this;
  }

   /**
   * Get referenceType
   * @return referenceType
  **/
  @ApiModelProperty(value = "")
  public ConceptMini getReferenceType() {
    return referenceType;
  }

  public void setReferenceType(ConceptMini referenceType) {
    this.referenceType = referenceType;
  }

  public TypeReferences referencingConcepts(CollectionConceptMini referencingConcepts) {
    this.referencingConcepts = referencingConcepts;
    return this;
  }

   /**
   * Get referencingConcepts
   * @return referencingConcepts
  **/
  @ApiModelProperty(value = "")
  public CollectionConceptMini getReferencingConcepts() {
    return referencingConcepts;
  }

  public void setReferencingConcepts(CollectionConceptMini referencingConcepts) {
    this.referencingConcepts = referencingConcepts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeReferences typeReferences = (TypeReferences) o;
    return Objects.equals(this.referenceType, typeReferences.referenceType) &&
        Objects.equals(this.referencingConcepts, typeReferences.referencingConcepts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceType, referencingConcepts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeReferences {\n");
    
    sb.append("    referenceType: ").append(toIndentedString(referenceType)).append("\n");
    sb.append("    referencingConcepts: ").append(toIndentedString(referencingConcepts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

