/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthoringStatsSummary;
import io.swagger.client.model.ConceptMicro;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthoringStatsApi
 */
@Ignore
public class AuthoringStatsApiTest {

    private final AuthoringStatsApi api = new AuthoringStatsApi();

    
    /**
     * getChangedFSNs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChangedFSNsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        List<ConceptMicro> response = api.getChangedFSNsUsingGET(branch, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * getInactivatedConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInactivatedConceptsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        List<ConceptMicro> response = api.getInactivatedConceptsUsingGET(branch, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * getInactivatedSynonyms
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInactivatedSynonymsUsingGETTest() throws ApiException {
        String branch = null;
        List<ConceptMicro> response = api.getInactivatedSynonymsUsingGET(branch);

        // TODO: test validations
    }
    
    /**
     * getNewConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNewConceptsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        List<ConceptMicro> response = api.getNewConceptsUsingGET(branch, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * getNewSynonymsOnExistingConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNewSynonymsOnExistingConceptsUsingGETTest() throws ApiException {
        String branch = null;
        List<ConceptMicro> response = api.getNewSynonymsOnExistingConceptsUsingGET(branch);

        // TODO: test validations
    }
    
    /**
     * getReactivatedConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReactivatedConceptsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        List<ConceptMicro> response = api.getReactivatedConceptsUsingGET(branch, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * getReactivatedSynonyms
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReactivatedSynonymsUsingGETTest() throws ApiException {
        String branch = null;
        List<ConceptMicro> response = api.getReactivatedSynonymsUsingGET(branch);

        // TODO: test validations
    }
    
    /**
     * Calculate statistics for unreleased/unversioned content to be used in daily build browser.
     *
     * Does not work on versioned content.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatsUsingGETTest() throws ApiException {
        String branch = null;
        AuthoringStatsSummary response = api.getStatsUsingGET(branch);

        // TODO: test validations
    }
    
}
