/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthoringStatsSummary;
import io.swagger.client.model.ConceptMicro;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthoringStatsApi
 */
@Ignore
public class AuthoringStatsApiTest {

    private final AuthoringStatsApi api = new AuthoringStatsApi();

    
    /**
     * getChangedFSNs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChangedFSNsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        List<ConceptMicro> response = api.getChangedFSNsUsingGET(branch, acceptLanguage);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getInactivatedConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInactivatedConceptsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        List<ConceptMicro> response = api.getInactivatedConceptsUsingGET(branch, acceptLanguage);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getInactivatedSynonyms
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInactivatedSynonymsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        List<ConceptMicro> response = api.getInactivatedSynonymsUsingGET(branch);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getNewConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNewConceptsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        List<ConceptMicro> response = api.getNewConceptsUsingGET(branch, acceptLanguage);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getNewSynonymsOnExistingConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNewSynonymsOnExistingConceptsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        List<ConceptMicro> response = api.getNewSynonymsOnExistingConceptsUsingGET(branch);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getReactivatedConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReactivatedConceptsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        List<ConceptMicro> response = api.getReactivatedConceptsUsingGET(branch, acceptLanguage);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * getReactivatedSynonyms
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReactivatedSynonymsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        List<ConceptMicro> response = api.getReactivatedSynonymsUsingGET(branch);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
    /**
     * Calculate statistics for unreleased/unversioned content to be used in daily build browser.
     *
     * Does not work on versioned content.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore //because ParseException
    @Test
    public void getStatsUsingGETTest() throws ApiException {
        String branch = "MAIN";
        AuthoringStatsSummary response = api.getStatsUsingGET(branch);

        //US 4_6 Server response
        System.out.println(response.toString());
        Assert.assertNotEquals(null,response);
    }
    
}
