/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CodeSystem;
import io.swagger.client.model.ItemsPageCodeSystem;
import io.swagger.client.model.ItemsPageCodeSystemVersion;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CodeSystemsApi
 */
@Ignore
public class CodeSystemsApiTest {

    private final CodeSystemsApi api = new CodeSystemsApi();

    
    /**
     * Retrieve all code systems
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllUsingGETTest() throws ApiException {
        ItemsPageCodeSystem response = api.findAllUsingGET();

        // TODO: test validations
    }
    
    /**
     * Retrieve all code system versions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllVersionsUsingGETTest() throws ApiException {
        String shortName = null;
        ItemsPageCodeSystemVersion response = api.findAllVersionsUsingGET(shortName);

        // TODO: test validations
    }
    
    /**
     * Retrieve a code system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findCodeSystemUsingGETTest() throws ApiException {
        String shortName = null;
        CodeSystem response = api.findCodeSystemUsingGET(shortName);

        // TODO: test validations
    }
    
}
