/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AsyncConceptChangeBatch;
import io.swagger.client.model.CollectionConceptMini;
import io.swagger.client.model.ConceptDescriptionsResult;
import io.swagger.client.model.ConceptMini;
import io.swagger.client.model.ConceptReferencesResult;
import io.swagger.client.model.ConceptView;
import io.swagger.client.model.Expression;
import io.swagger.client.model.ExpressionStringPojo;
import io.swagger.client.model.InboundRelationshipsResult;
import io.swagger.client.model.ItemsPageConcept;
import io.swagger.client.model.ItemsPageConceptMini;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConceptsApi
 */
@Ignore
public class ConceptsApiTest {

    private final ConceptsApi api = new ConceptsApi();

    
    /**
     * Load a concept in the browser format.
     *
     * During content authoring previous versions of the concept can be loaded from version control. To do this use the branch path format {branch@yyyy-MM-ddTHH:mm:ss.SSSZ} or {branch@epoch_milliseconds}. The version of the concept when the branch was created can be loaded using {branch@-}.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBrowserConceptUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        ConceptView response = api.findBrowserConceptUsingGET(branch, conceptId, acceptLanguage);

        // TODO: test validations
        System.out.println(response);
    }
    
    /**
     * findConceptAncestors
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptAncestorsUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        String form = null;
        CollectionConceptMini response = api.findConceptAncestorsUsingGET(branch, conceptId, acceptLanguage, form);

        // TODO: test validations
    }
    
    /**
     * findConceptChildren
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptChildrenUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        String form = null;
        CollectionConceptMini response = api.findConceptChildrenUsingGET(branch, conceptId, acceptLanguage, form);

        // TODO: test validations
    }
    
    /**
     * findConceptDescendants
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptDescendantsUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        Boolean stated = null;
        Integer offset = null;
        Integer limit = null;
        ItemsPageConceptMini response = api.findConceptDescendantsUsingGET(branch, conceptId, acceptLanguage, stated, offset, limit);

        // TODO: test validations
    }
    
    /**
     * findConceptDescriptions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptDescriptionsUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        ConceptDescriptionsResult response = api.findConceptDescriptionsUsingGET(branch, conceptId, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * findConceptInboundRelationships
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptInboundRelationshipsUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        InboundRelationshipsResult response = api.findConceptInboundRelationshipsUsingGET(branch, conceptId);

        // TODO: test validations
    }
    
    /**
     * findConceptParents
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptParentsUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        String form = null;
        CollectionConceptMini response = api.findConceptParentsUsingGET(branch, conceptId, acceptLanguage, form);

        // TODO: test validations
    }
    
    /**
     * Find concepts which reference this concept in the inferred or stated form (including stated axioms).
     *
     * Pagination works on the referencing concepts. A referencing concept may have one or more references of different types.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptReferencesUsingGETTest() throws ApiException {
        String branch = null;
        Long conceptId = null;
        String acceptLanguage = null;
        Boolean stated = null;
        Integer offset = null;
        Integer limit = null;
        ConceptReferencesResult response = api.findConceptReferencesUsingGET(branch, conceptId, acceptLanguage, stated, offset, limit);

        // TODO: test validations
    }
    
    /**
     * findConcept
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        ConceptMini response = api.findConceptUsingGET(branch, conceptId, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * findConcepts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findConceptsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        Boolean activeFilter = null;
        String definitionStatusFilter = null;
        String term = null;
        Boolean termActive = null;
        String ecl = null;
        String statedEcl = null;
        List<String> conceptIds = null;
        Integer offset = null;
        Integer limit = null;
        String searchAfter = null;
        ItemsPageConceptMini response = api.findConceptsUsingGET(branch, acceptLanguage, activeFilter, definitionStatusFilter, term, termActive, ecl, statedEcl, conceptIds, offset, limit, searchAfter);

        // TODO: test validations
    }
    
    /**
     * Load concepts in the browser format.
     *
     * When enabled &#39;searchAfter&#39; can be used for unlimited pagination. Load the first page then take the &#39;searchAfter&#39; value from the response and use that as a parameter in the next page request instead of &#39;number&#39;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBrowserConceptsUsingGETTest() throws ApiException {
        String branch = null;
        String acceptLanguage = null;
        Integer number = null;
        Integer size = null;
        String searchAfter = null;
        ItemsPageConcept response = api.getBrowserConceptsUsingGET(branch, acceptLanguage, number, size, searchAfter);

        // TODO: test validations
    }
    
    /**
     * getConceptAuthoringForm
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptAuthoringFormUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        Expression response = api.getConceptAuthoringFormUsingGET(branch, conceptId, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Fetch the status of a bulk concept creation or update.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptBulkChangeUsingGETTest() throws ApiException {
        String branch = null;
        String bulkChangeId = null;
        AsyncConceptChangeBatch response = api.getConceptBulkChangeUsingGET(branch, bulkChangeId);

        // TODO: test validations
    }
    
    /**
     * getConceptNormalForm
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptNormalFormUsingGETTest() throws ApiException {
        String branch = null;
        String conceptId = null;
        String acceptLanguage = null;
        Boolean statedView = null;
        Boolean includeTerms = null;
        ExpressionStringPojo response = api.getConceptNormalFormUsingGET(branch, conceptId, acceptLanguage, statedView, includeTerms);

        // TODO: test validations
    }
    
}
