/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ItemsPageConceptMini;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MrcmXmlApi
 */
@Ignore
public class MrcmXmlApiTest {

    private final MrcmXmlApi api = new MrcmXmlApi();

    
    /**
     * Retrieve valid values for the given attribute and term prefix.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore //because "Expected BEGIN_OBJECT but was BEGIN_ARRAY"
    @Test
    public void retrieveAttributeValuesUsingGETTest() throws ApiException {
        String path = "MAIN";
        String attributeId = "116680003";
        String termPrefix = "Is a";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        ItemsPageConceptMini response = api.retrieveAttributeValuesUsingGET(path, attributeId, termPrefix, acceptLanguage);

        //US 4_6 Server response
        System.out.println(response.toString());
        // TODO: test validations
    }
    
    /**
     * Retrieve MRCM domain attributes applicable for the given parents.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore //because "Expected BEGIN_OBJECT but was BEGIN_ARRAY"
    @Test
    public void retrieveDomainAttributesUsingGETTest() throws ApiException {
        String path = "MAIN";
        String acceptLanguage = "en-X-900000000000509007,en-X-900000000000508004,en";
        List<Long> parentIds = null;
        ItemsPageConceptMini response = api.retrieveDomainAttributesUsingGET(path, acceptLanguage, parentIds);

        // TODO: test validations
    }
    
}
