/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ItemsPageConceptMini;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MrcmXmlApi
 */
@Ignore
public class MrcmXmlApiTest {

    private final MrcmXmlApi api = new MrcmXmlApi();

    
    /**
     * Retrieve valid values for the given attribute and term prefix.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAttributeValuesUsingGETTest() throws ApiException {
        String path = null;
        String attributeId = null;
        String termPrefix = null;
        String acceptLanguage = null;
        ItemsPageConceptMini response = api.retrieveAttributeValuesUsingGET(path, attributeId, termPrefix, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Retrieve MRCM domain attributes applicable for the given parents.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveDomainAttributesUsingGETTest() throws ApiException {
        String path = null;
        String acceptLanguage = null;
        List<Long> parentIds = null;
        ItemsPageConceptMini response = api.retrieveDomainAttributesUsingGET(path, acceptLanguage, parentIds);

        // TODO: test validations
    }
    
}
