/*
 * Snowstorm
 * SNOMED CT Terminology Server REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InactivationTypeAndConceptIdList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ValidationApi
 */
@Ignore
public class ValidationApiTest {

    private final ValidationApi api = new ValidationApi();

    
    /**
     * Find inactive concepts with no historical association grouped by inactivation type.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore //because socketTimeOut
    @Test
    public void findInactiveConceptsWithNoHistoricalAssociationByInactivationTypeUsingGETTest() throws ApiException {
        String branch = "MAIN";
        String conceptEffectiveTime = null;
        List<InactivationTypeAndConceptIdList> response = api.findInactiveConceptsWithNoHistoricalAssociationByInactivationTypeUsingGET(branch,conceptEffectiveTime);

        //US 4_6 Server response
        System.out.println(response.toString());
        // TODO: test validations
    }
    
}
